timeout = 30000
enableInlineShortcodes = true

[taxonomies]
category = "switch游戏推荐"
tag = "游戏类型"
archives = "最近更新"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
    disableInlineCSS = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
